// ********************************************************
// ** basicraiddr.c **
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License. 
// 
// Version: 1.0.0
// Author: Brett Dodds (brett.dodds@microsoft.com)
// (C) Microsoft Corp. - Distributed under NDA
// 
// For example simulation of Basic RAIDDR
// This can serve as a reference for hardware implementation
// 
// This example demonstrates implementation using 10x4 DDR5
//    DIMMs and using 4 codewords to get between 0 and 12
//    bits of metadata
// ********************************************************

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

// *** CRC Using coefficients ***
// The idea is that each bit in a codeword has an associated coefficient which is the CRC result if that
//  bit were the only bit set in the codeword.
// Because CRC is a linear code, we can compute the full CRC by adding (XOR) the CRC coefficient of each
//  position where a bit is set within the codeword. This can significantly speed up CRC calculation,
//  especially for longer codewords

// -- CreateCrcCoefficients --
// Generates CRC coefficients for a given polynomial and code length
// In implementation, these coefficiencts could be precomputed and wired in hardware or generated by
//  firmware and loaded into registers. Firmware method gives flexibility to change encoding boot-to-boot.
// Inputs:
//  bits: IN, total number of bits in the codeword (including userdata, metadata, and CRC bits)
//  polynomial: IN, base polynomial of the CRC, should be a primitive polynomial, reversed bit order with
//    hightest-order term suppressed
//    Ex: CRC-12: Primitive = x^12 + x^10 + x^2 + x^1 + x^0 (0x1407) --> Remove x^12: 0x407 --> Reverse: 0xE02
//        CRC-16: Primitive = x^16 + x^15 + x^12 + x^10 + x^0 (0x19401) --> Remove x^16: 0x9401 --> Reverse: 0x8029
//  pCoefficients: OUT, pre-allocated array for coefficients, must be 'bits' in length
//    Coefficients are ordered such that MSB (coefficient index bits-1) is equivalent to last codeword
// ReturnValue: 0 if successful, -1 if overlapping coefficients 
int CreateCrcCoefficients(int bits, uint64_t polynomial, uint64_t* pCoefficients)
{
    // Because CRC is circular, we could start the coefficients at any non-zero value, in our case we
    // just start with the modified polynomial itself
    // Entries are populated from top to bottom (last entry first)
    // Each entry is computed using a CRC shift of the previous (higher-indexed) entry
    // e.g. Entry3 = (Entry4 >> 1) XOR (if shifted-out bit ==1 then 'polynomial', 0 otherwise)
    uint64_t v = pCoefficients[--bits] = polynomial;
    while (bits--)
        v = pCoefficients[bits] = (v >> 1) ^ ((v & 1) ? polynomial : 0);
    return 0;
}

// -- GetCrc --
// Generates CRC for a given set of bits within a codeword by adding (XOR) the CRC coefficient of each
//   corresponding bit that is set ('1') in the codeword
// Inputs:
//   d: IN, Data to generate CRC on
//   coeff[]: IN, Array of coefficients corresponding to bit locations (generated above)
//   offset: IN, Offset within coefficients array which correspond to bit0 of 'd'
// ReturnValue: CRC for the given bits at the given offset
uint64_t GetCrc(uint64_t d, const uint64_t coeff[], int offset)
{
    uint64_t crc = 0;               // Initialize returnvalue to 0
    while (d)                       // Work below is only relevant when there are 1's in the data
    {
        if (d & 1)                  // If the bit is set in the data
            crc ^= coeff[offset];   // Then add in this bit's corresponding coefficient
        d >>= 1;                    // Move to the next data bit
        offset++;                   // Adjust index to the next bit's coefficient
    }
    return crc;                     // Return crc corresponding to this isolated data
}

// -- EncodeRaiddr_D510x4 --
// Encode user data to dram data using Basic RAIDDR
// Inputs:
//   data: IN, Data to encode
//   metadata: IN, Metadata to encode
//   metadatabits: IN, # of bits of metadata
//   crcconstants_s: IN, Coefficients for codeword_0
//   crcconstants: IN, Coefficients for codeword_1,2,etc...
//   codeword: OUT, RAIDDR-encoded data
// ReturnValue: 0 when successful (always successful)
int EncodeRaiddr_D510x4(uint64_t data[8], uint16_t metadata, int metadatabits, uint64_t crcconstants_s[], uint64_t crcconstants[], uint64_t codeword[10])
{
    int sym, cw;
    uint16_t scw_symdata[4][9]; // Helper array, data split into codewords
    uint64_t scw_symcrc; // Holds results from CRC calculations
    const int SYM_CRC = 8;
    const int SYM_XOR = 9;
    const int CW = 4;

    // Build CW0 codeword (includes lower 16 bits of each data symbol and metadata)
    for (sym = 0; sym < SYM_CRC; sym++)
        scw_symdata[0][sym] = (uint16_t)(data[sym]);
    scw_symdata[0][SYM_CRC] = metadata & ((1 << metadatabits) - 1); // Mask off unused metadata bits... just in case it didn't come that way already;
    // Compute CRC for CW0
    // Note: In GetCrc function, we pass offset +12 in addition to expected 16*sym for bit position alignment
    //       this is because we are creating a CRC value and the last bit of the data must correspond with the
    //       last bit in the CRC coefficients table. When we decode the data, bits from the CRC will be included
    //       and during CRC verification we do not add this addition offset since the last bit from the stored
    //       CRC value will correspond with the last bit in the CRC coefficients table.
    scw_symcrc = 0;
    for (sym = 0; sym < SYM_XOR; sym++)
        scw_symcrc ^= GetCrc(scw_symdata[0][sym], crcconstants_s, 16 * sym + 12);
    // Create the CW0 CRC symbol and initialize the output codeword to include userdata, metadata, and the CW0 CRC symbol
    scw_symdata[0][SYM_CRC] |= (uint16_t)(scw_symcrc << metadatabits);
    memcpy(codeword, data, sizeof(uint64_t) * 8);
    codeword[SYM_CRC] = scw_symdata[0][SYM_CRC];

    for (cw = 1; cw < CW; cw++)
    {
        // Build cw# codeword (includes the cw'th 16 bits of each data symbol XOR'd with the lower 16 bits of each data symbol)
        for (sym = 0; sym < SYM_CRC; sym++)
            scw_symdata[cw][sym] = (uint16_t)(data[sym] >> (16 * cw)) ^ scw_symdata[0][sym];
        // Compute CRC for CW# cw: See note above, and notice the +16 offset here (due to CRC-16 used)
        scw_symcrc = 0;
        for (sym = 0; sym < SYM_CRC; sym++)
            scw_symcrc ^= GetCrc(scw_symdata[cw][sym], crcconstants, 16 * sym + 16);
        // Add cw CRC to the output codeword
        codeword[SYM_CRC] |= (uint64_t)(scw_symcrc ^ scw_symdata[0][SYM_CRC]) << (16 * cw);
    }

    // Generate XOR symbol. Very simple bitwise XOR of all other symbols
    codeword[SYM_XOR] = codeword[0];
    for (sym = 1; sym < SYM_XOR; sym++)
        codeword[SYM_XOR] ^= codeword[sym];

    return 0;
}

// -- DecodeRaiddr_D510x4 --
// Decode dram data encoded with Basic RAIDDR
// Inputs:
//   codeword: IN, RAIDDR-encoded data
//   metadatabits: IN, # of bits of metadata
//   crcconstants_s: IN, Coefficients for codeword_0
//   crcconstants: IN, Coefficients for codeword_1,2,etc...
//   data: OUT, decoded and corrected data
//   pmetadata: OUT, decoded and corrected metadata
//   pcedev: OUT, device which had the error
//   pcemask: OUT, detected error mask
// ReturnValue: 0 = NoError, 1 = CE, 2 = UE (multi-device overlap), 3 = UE (gap pattern), 4 = UE (multi-device no solution)
int DecodeRaiddr_D510x4(uint64_t codeword[10], int metadatabits, uint64_t crcconstants_s[], uint64_t crcconstants[], uint64_t data[8], uint16_t* pmetadata, int* pcedev, uint64_t* pcemask)
{
    int sym, cw;
    uint16_t subcodeword[4][9]; // Helper array, splits codeword into smaller codewords
    uint64_t ceMask; // Full symbol-level error mask
    uint16_t errmask[4]; // Subcodeword symbol-level error masks
    uint16_t mdm = (1 << metadatabits) - 1; // Metadata mask
    uint64_t trialdata[10]; // Stores trial results (CRC calculations)

    int passingTrial = -1; // SymbolId of passing trial
    const int S_COUNT = 10; // Symbol count
    const int SYM_XOR = S_COUNT - 1; // XOR symbol number
    const int SYM_CRC = S_COUNT - 2; // CRC symbol number
    const int CW = 4; // Sub-codeword count

    // Generate the Full symbol and subcodeword symbol error masks by XOR'ing all symbols together
    ceMask = codeword[0];
    for (sym = 1; sym < S_COUNT; sym++)
        ceMask ^= codeword[sym];
    for (cw = 0; cw < CW; cw++)
        errmask[cw] = (uint16_t)(ceMask >> (16 * cw));

    // Build sub-codewords (includes all data, metadata, and stored crc values)
    // Note that codewords 1,2,etc... are XOR'd entirely with codeword 0
    //   This is because it helps us to have larger gap patterns (less likely to happen)
    for (sym = 0; sym < SYM_XOR; sym++)
        subcodeword[0][sym] = (uint16_t)codeword[sym];
    for (cw = 1; cw < CW; cw++)
        for (sym = 0; sym < SYM_XOR; sym++)
            subcodeword[cw][sym] = (uint16_t)(codeword[sym] >> (16 * cw)) ^ subcodeword[0][sym];

    // Generate CRC values and store as XOR device trial
    //   Essentially, if there are only failures in the XOR device, this should resolve to 00's
    trialdata[SYM_XOR] = 0;
    for (sym = 0; sym < SYM_XOR; sym++)
        trialdata[SYM_XOR] ^= GetCrc(subcodeword[0][sym], crcconstants_s, 16 * sym);
    for (cw = 1; cw < CW; cw++)
        for (sym = 0; sym < SYM_XOR; sym++)
            trialdata[SYM_XOR] ^= GetCrc(subcodeword[cw][sym], crcconstants, 16 * sym) << (16 * cw);

    // TRIALS - Generate Mask CRC values of the error mask at each die position
    // 
    // Due to linearity of code, we can simply calculate the CRC of the error mask itself at each
    // position. A passing trial will have the same CRC result as we computed above for the full
    // CRC. Therefore, we XOR the result with the CRC result (that we stored in trialdata[SYM_XOR]).
    // 
    // The beauty of the CRC by coefficient implementation is that this can be done completely in
    // parallel. Since each bit position has its own coefficient, all these trials are done at the
    // same time without affecting other trials or needing the same hardware.
    for (sym = 0; sym < SYM_XOR; sym++)
    {
        trialdata[sym] = GetCrc(errmask[0], crcconstants_s, 16 * sym);
        for (cw = 1; cw < CW; cw++)
            trialdata[sym] |= GetCrc(errmask[cw] ^ errmask[0], crcconstants, 16 * sym) << (16 * cw);
        trialdata[sym] ^= trialdata[9];
    }

    // Preload return data with codeword data
    memcpy(data, codeword, sizeof(uint64_t) * 8);
    if (pmetadata) *pmetadata = codeword[SYM_CRC] & mdm;
    
    // Preload Telemetry
    if (pcemask) *pcemask = ceMask;
    if (pcedev) *pcedev = -1;

    // Evaluate results from trials
    if (ceMask == 0 && trialdata[SYM_XOR] == 0) // No errors detected in FailureMask nor CRC
        return 0; // Data is good
    if (ceMask == 0 && trialdata[SYM_XOR] != 0) // No errors detected in FailureMask, but CRC detected -- Multi-device overlapping failure
        return 2; // Uncorrectable

    // We did detect an error that may be correctable.
    // Determine which device the error was on...
    passingTrial = -1;
    for (sym = 0; sym < S_COUNT; sym++)
        if (trialdata[sym] == 0)
        {
            if (passingTrial >= 0) // If we already identified a passing trial...
                return 3; // Uncorrectable, more than 1 passing trial -- Gap pattern or Multi-device failure
            passingTrial = sym;
        }
    if (passingTrial < 0) // If there were no passing trials...
        return 4; // Uncorrectable, no passing trial -- Multi-device failure

    // At this point we know we identified one failing device
    // Now we just update the data (if needed) and return '1' (CE error)
    if (pcedev) *pcedev = passingTrial; // Telemetry update

    if (passingTrial < 8) // If the problem covered the user data...
    {
        data[passingTrial] ^= ceMask; // Correct the user data
        return 1; // Corrected error
    }

    if (passingTrial == 8 && pmetadata)
    {
        *pmetadata ^= ceMask & mdm;
        return 1; // Corrected error
    }

    return 1; // Corrected error on XOR device (which has no data)
}

///////////////////////////////////////////////////////////////
// The below functions are simply for testing the Encode/Decode

#define BACKGROUNDS_TO_TRY          1000
#define CORRUPTIONS_PER_BACKGROUND  50000

#define CLRLINE "\x1b[2K\r"     // Line clearing escape sequence

uint64_t NextRand(uint64_t v)
{
    return (v >> 1) ^ ((v & 1) ? 0x8040000020000004 : 0);
}

int main(int argc, char* argv[])
{
    uint64_t codeword[10]; // RAIDDR-encoded codeword
    uint64_t userdata[8]; // Data to encode
    uint16_t metadata; // Metadata to encode
    uint64_t returnuserdata[8]; // Data from decoder
    uint16_t returnmetadata; // Metadata from decoder
    int ceDevice; // Telmetry - Device number that failed
    uint64_t ceMask; // Telemetry - Failure mask that had to be applied to ceDevice
    uint64_t* coeffA = NULL; // 'Short' CRC coefficients (used as crcconstants_s)
    uint64_t* coeffB = NULL; // Normal CRC coefficients (used as crcconstants) 

    uint64_t v, corruption; // temporary, corruption to apply to the codeword
    int d, result; // temporary, result from decode

    // Helper constants for the DDR5 10x4 4CW 4MD case
    const int metadatabits = 4;
    const int codeWords = 4;
    const int devices = 10;
    const int cwBitsPerDev = 64 / codeWords;
    const int cwSize = cwBitsPerDev * (devices - 1);

    // Simulation iterators and statistics
    const uint64_t bgToTest = BACKGROUNDS_TO_TRY; // 1000 error patterns to evaluate (default)
    const uint64_t errPerBg = CORRUPTIONS_PER_BACKGROUND; // 50000 error patterns per background (default)
    uint64_t bgNum;
    uint64_t errNum;
    uint64_t eval;
    uint64_t uecount;
    uint64_t sdccount;
    double totalden;

    // Create CRC coefficients
    // Note that the polynomial is only used to generate these coefficients
    // After that, there is nowhere it is used in the encode/decode
    coeffA = (uint64_t*)malloc(sizeof(uint64_t) * cwSize);
    CreateCrcCoefficients(cwSize, 0xE02, coeffA); // 0xE02 is a reverse, truncated, primitive polynomial for CRC-12
    if (codeWords > 1)
    {
        coeffB = (uint64_t*)malloc(sizeof(uint64_t) * cwSize);
        CreateCrcCoefficients(cwSize, 0x8029, coeffB); // 0x8029 is a reverse, truncated, primitive polynomial for CRC-16
    }
    metadata = 1; // Initialize Metadata

    // Initialize Userdata to random values
    v = userdata[0] = 0xABCDEF0123456789;
    for (d = 1; d < 8; d++)
        v = userdata[d] = NextRand(v); // LFSR for random data

    // Stage-1
    // We want to evaluate random backgrounds, random error patterns. This will cycle
    // through 'bgToTest' number different backgrounds and evaluate 'errPerBg' number
    // of different error cases for each background pattern.
    // We cycle through each device to take the error to not bias any specific device.
    // 
    // In reality, RAIDDR uses linear codes which makes it background-independent and
    // RAIDDR is technically device-position independent, but it's still valuable to
    // validate those claims in test.
    eval = 0;
    uecount = sdccount = 0;
    corruption = 1; // Initialize corruption data
    for (bgNum = 0; bgNum < bgToTest; bgNum++)
    {
        // Create new background...
        for (d = 0; d < 8; d++)
            userdata[d] = NextRand(userdata[d]); // LFSR randomization
        metadata = (metadata >> 1) ^ ((metadata & 1) ? 0xC : 0); // LFSR randomization

        // Raiddr encode the new background data
        EncodeRaiddr_D510x4(userdata, metadata, metadatabits, coeffA, coeffB, codeword);

        // Screen update
        if (eval)
        {
            printf(CLRLINE "Stage-1: %.1f%% (%" SCNu64 ") - SDC:%" SCNu64 " - UE:%" SCNu64 " (Pue=%.3le) (Gran=%.3le)", (double)eval * 100.0 / (double)bgToTest / (double)errPerBg, eval, sdccount, uecount, (double)uecount / (double)eval, 1.0 / (double)eval);
            fflush(stdout);
        }

        // Verify RAIDDR works when there is no corruption - Show on screen if this didn't work
        result = DecodeRaiddr_D510x4(codeword, metadatabits, coeffA, coeffB, returnuserdata, &returnmetadata, &ceDevice, &ceMask);
        if (result != 0)
            printf(CLRLINE " NoError Fail: result=%d\n", result);

        // Evaluate 'errPerBg' number of different corruption types with this background
        for (errNum = 0; errNum < errPerBg; errNum++) // This loop evaluates different data corruption cases
        {
            corruption = NextRand(corruption); // Next random data pattern (LFSR)
            // Decode corrupted Raiddr codeword and analyze results
            codeword[d] ^= corruption; // Add corruption to the codeword
            result = DecodeRaiddr_D510x4(codeword, metadatabits, coeffA, coeffB, returnuserdata, &returnmetadata, &ceDevice, &ceMask);
            codeword[d] ^= corruption; // Remove corruption from the codeword
            if (result == 2 || result == 3 || result == 4) // Uncorrectable error
                uecount++;
            else if (result == 0) // Decoder said data was good, but we know it wasn't
                sdccount++;
            else if (ceDevice != d || ceMask != corruption) // Corrected or said it's good, so let's verify the output
                sdccount++;
            eval++;
            if (++d >= devices) d = 0; // Apply corruption on next device for the next loop
        }
    }
    printf(CLRLINE "Stage-1 Summary: Evals=%" SCNu64 " SDC=%" SCNu64 " UE=%" SCNu64 " (%.3le)\n", eval, sdccount, uecount, (double)uecount / (double)eval);

    // Stage-2: Evaluate gap-capable patterns:
    // Now evaluate all error cases where the error is the same across all codewords
    // -- these are the only possible gap pattern cases for single-die failure
    // There are 15 total gap patterns in the DDR5 10x4 4-CW 4-MD configuration.
    // Assuming everything works properly, this step should fail 15/65536 (0.00022888 ratio)
    eval = 0;
    uecount = sdccount = 0;
    for (errNum = 1; errNum < (1 << 16); errNum++)
    {
        corruption = (uint64_t)errNum | ((uint64_t)errNum << 16) | ((uint64_t)errNum << 32) | ((uint64_t)errNum << 48); // Note duplicate error patterns in each codeword, these are where the gaps are
        for (d = 0; d < devices; d++) // Use the same corruption in all devices... this verifies for us that gaps are gaps for all devies
        {
            // Decode corrupted Raiddr codeword and analyze results
            codeword[d] ^= corruption; // Add corruption to the codeword
            result = DecodeRaiddr_D510x4(codeword, metadatabits, coeffA, coeffB, returnuserdata, &returnmetadata, &ceDevice, &ceMask);
            codeword[d] ^= corruption; // Remove corruption from the codeword
            if (result == 2 || result == 3 || result == 4) // Uncorrectable error
                uecount++;
            else if (result == 0) // Decoder said data was good, but we know it wasn't
                sdccount++;
            else if (ceDevice != d || ceMask != corruption) // Corrected or said it's good, so let's verify the output
                sdccount++;
            eval++;
        }
    }
    printf(CLRLINE "Stage-2 Summary: Evals=%" SCNu64 " SDC=%" SCNu64 " UE=%" SCNu64 " (%.3le)\n", eval, sdccount, uecount, (double)uecount / (double)eval);
    totalden = (1.0 + (double)((uint64_t)-1)) * 10.0; // 1^64 combinations on 10 different die
    printf(CLRLINE "Overall SDDC: SDC=%.3le UE=%.3le\n", (double)sdccount / totalden, (double)uecount / totalden);

    // Tidy up memory
    if (coeffA)
        free(coeffA);
    if (coeffB)
        free(coeffB);

    return 0;
}