// *** RAIDDR_Basic_DDR5_4MD_4CW.v ***
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Example Basic RAIDDR RTL File generated by "raiddrinit"
// Questions? Contact: Brett Dodds (brett.dodds@microsoft.com)
// Settings:
//   Symbols:          10
//   Symbol size:      64 bits
//   Sub-CodeWords:    4
//   Metadata bits:    4
//   ECC gap patterns: 15
//     0x16cd16cd16cd16cd
//     0x2d9a2d9a2d9a2d9a
//     0x3b573b573b573b57
//     0x5b345b345b345b34
//     0x4df94df94df94df9
//     0x76ae76ae76ae76ae
//     0x6063606360636063
//     0xb668b668b668b668
//     0xa0a5a0a5a0a5a0a5
//     0x9bf29bf29bf29bf2
//     0x8d3f8d3f8d3f8d3f
//     0xed5ced5ced5ced5c
//     0xfb91fb91fb91fb91
//     0xc0c6c0c6c0c6c0c6
//     0xd60bd60bd60bd60b

module raiddr_crcconstants_10x16x4_4m(
    output reg [15:0] v[143:0],
    output reg [11:0] vs[143:0]
);
    assign v = {
        16'h8029, 16'hc03d, 16'he037, 16'hf032, 16'h7819, 16'hbc25, 16'hde3b, 16'hef34,
        16'h779a, 16'h3bcd, 16'h9dcf, 16'hcece, 16'h6767, 16'hb39a, 16'h59cd, 16'haccf,
        16'hd64e, 16'h6b27, 16'hb5ba, 16'h5add, 16'had47, 16'hd68a, 16'h6b45, 16'hb58b,
        16'hdaec, 16'h6d76, 16'h36bb, 16'h9b74, 16'h4dba, 16'h26dd, 16'h9347, 16'hc98a,
        16'h64c5, 16'hb24b, 16'hd90c, 16'h6c86, 16'h3643, 16'h9b08, 16'h4d84, 16'h26c2,
        16'h1361, 16'h8999, 16'hc4e5, 16'he25b, 16'hf104, 16'h7882, 16'h3c41, 16'h9e09,
        16'hcf2d, 16'he7bf, 16'hf3f6, 16'h79fb, 16'hbcd4, 16'h5e6a, 16'h2f35, 16'h97b3,
        16'hcbf0, 16'h65f8, 16'h32fc, 16'h197e, 16'h0cbf, 16'h8676, 16'h433b, 16'ha1b4,
        16'h50da, 16'h286d, 16'h941f, 16'hca26, 16'h6513, 16'hb2a0, 16'h5950, 16'h2ca8,
        16'h1654, 16'h0b2a, 16'h0595, 16'h82e3, 16'hc158, 16'h60ac, 16'h3056, 16'h182b,
        16'h8c3c, 16'h461e, 16'h230f, 16'h91ae, 16'h48d7, 16'ha442, 16'h5221, 16'ha939,
        16'hd4b5, 16'hea73, 16'hf510, 16'h7a88, 16'h3d44, 16'h1ea2, 16'h0f51, 16'h8781,
        16'hc3e9, 16'he1dd, 16'hf0c7, 16'hf84a, 16'h7c25, 16'hbe3b, 16'hdf34, 16'h6f9a,
        16'h37cd, 16'h9bcf, 16'hcdce, 16'h66e7, 16'hb35a, 16'h59ad, 16'hacff, 16'hd656,
        16'h6b2b, 16'hb5bc, 16'h5ade, 16'h2d6f, 16'h969e, 16'h4b4f, 16'ha58e, 16'h52c7,
        16'ha94a, 16'h54a5, 16'haa7b, 16'hd514, 16'h6a8a, 16'h3545, 16'h9a8b, 16'hcd6c,
        16'h66b6, 16'h335b, 16'h9984, 16'h4cc2, 16'h2661, 16'h9319, 16'hc9a5, 16'he4fb,
        16'hf254, 16'h792a, 16'h3c95, 16'h9e63, 16'hcf18, 16'h678c, 16'h33c6, 16'h19e3
    };
    assign vs = {
        12'he02, 12'h701, 12'hd82, 12'h6c1, 12'hd62, 12'h6b1, 12'hd5a, 12'h6ad,
        12'hd54, 12'h6aa, 12'h355, 12'hfa8, 12'h7d4, 12'h3ea, 12'h1f5, 12'hef8,
        12'h77c, 12'h3be, 12'h1df, 12'heed, 12'h974, 12'h4ba, 12'h25d, 12'hf2c,
        12'h796, 12'h3cb, 12'hfe7, 12'h9f1, 12'hafa, 12'h57d, 12'hcbc, 12'h65e,
        12'h32f, 12'hf95, 12'h9c8, 12'h4e4, 12'h272, 12'h139, 12'he9e, 12'h74f,
        12'hda5, 12'h8d0, 12'h468, 12'h234, 12'h11a, 12'h08d, 12'he44, 12'h722,
        12'h391, 12'hfca, 12'h7e5, 12'hdf0, 12'h6f8, 12'h37c, 12'h1be, 12'h0df,
        12'he6d, 12'h934, 12'h49a, 12'h24d, 12'hf24, 12'h792, 12'h3c9, 12'hfe6,
        12'h7f3, 12'hdfb, 12'h8ff, 12'ha7d, 12'hb3c, 12'h59e, 12'h2cf, 12'hf65,
        12'h9b0, 12'h4d8, 12'h26c, 12'h136, 12'h09b, 12'he4f, 12'h925, 12'ha90,
        12'h548, 12'h2a4, 12'h152, 12'h0a9, 12'he56, 12'h72b, 12'hd97, 12'h8c9,
        12'ha66, 12'h533, 12'hc9b, 12'h84f, 12'ha25, 12'hb10, 12'h588, 12'h2c4,
        12'h162, 12'h0b1, 12'he5a, 12'h72d, 12'hd94, 12'h6ca, 12'h365, 12'hfb0,
        12'h7d8, 12'h3ec, 12'h1f6, 12'h0fb, 12'he7f, 12'h93d, 12'ha9c, 12'h54e,
        12'h2a7, 12'hf51, 12'h9aa, 12'h4d5, 12'hc68, 12'h634, 12'h31a, 12'h18d,
        12'hec4, 12'h762, 12'h3b1, 12'hfda, 12'h7ed, 12'hdf4, 12'h6fa, 12'h37d,
        12'hfbc, 12'h7de, 12'h3ef, 12'hff5, 12'h9f8, 12'h4fc, 12'h27e, 12'h13f,
        12'he9d, 12'h94c, 12'h4a6, 12'h253, 12'hf2b, 12'h997, 12'hac9, 12'hb66
    };
endmodule

module raiddr_enc(
    input [511:0] data,
    input [3:0] metadata,
    output [639:0] codeword
);
    wire [15:0] crcconstants[143:0];
    wire [11:0] crcconstants_s[143:0];
    raiddr_crcconstants_10x16x4_4m crcconstants_inst(
       .v(crcconstants),
       .vs(crcconstants_s)
    );
    raiddr_encode #(.S_SZ(16), .CW(4), .MD(4), .S_COUNT(10)) encoder(
        .data(data),
        .metadata(metadata),
        .crcconstants(crcconstants),
        .crcconstants_s(crcconstants_s),
        .codeword(codeword)
    );
endmodule

module raiddr_dec(
    input [639:0] codeword,
    output [511:0] data,
    output [3:0] metadata,
    output reg ue,
    output reg ce,
    output reg [63:0] ceMask,
    output reg [9:0] symMask
);
    wire [15:0] crcconstants[143:0];
    wire [11:0] crcconstants_s[143:0];
    raiddr_crcconstants_10x16x4_4m crcconstants_inst(
       .v(crcconstants),
       .vs(crcconstants_s)
    );
    raiddr_decode #(.S_SZ(16), .CW(4), .MD(4), .S_COUNT(10)) decoder(
        .codeword(codeword),
        .crcconstants(crcconstants),
        .crcconstants_s(crcconstants_s),
        .data(data),
        .metadata(metadata),
        .ue(ue),
        .ce(ce),
        .ceMask(ceMask),
        .symMask(symMask)
    );
endmodule

// *** End of Generated RAIDDR Initialization

// ** basicraiddr_rtlbase.v **
// Version: 1.0.1
// Author: Brett Dodds (brett.dodds@microsoft.com)
// (C) Microsoft Corp. - Distributed under NDA
//
// For appending to .v files generated by raiddrinit
// Use as a reference only

module calccrc #(
    parameter LENGTH = 144,
    parameter WIDTH = 16
) (
    input [LENGTH-1:0] data,
    input [WIDTH-1:0] constants[LENGTH-1:0],
    output [WIDTH-1:0] crc
);
    wire [LENGTH-1:0] xorbit[WIDTH-1:0];
    genvar l, b;
    generate
        for (b = 0; b < WIDTH; b = b + 1) begin
            for (l = 0; l < LENGTH; l = l + 1) begin
                assign xorbit[b][l] = data[l] ? constants[l][b] : 0;
            end
            assign crc[b] = ^xorbit[b];
        end
    endgenerate
endmodule

module raiddr_encode #(
    parameter S_SZ = 16,
    parameter CW = 4,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [(S_COUNT-2)*S_SZ*CW-1:0] data,
    input [MD-1:0] metadata,
    input [S_SZ-1:0] crcconstants[(S_COUNT-1)*S_SZ-1:0],
    input [S_SZ-MD-1:0] crcconstants_s[(S_COUNT-1)*S_SZ-1:0],
    output [S_COUNT*S_SZ*CW-1:0] codeword
);
    localparam FS_SZ = S_SZ*CW; // Full Symbol Size = SymbolSize*CodeWords
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam SHB = S_SZ-1; // Symbol High Bit
    wire [SYM_CRC*S_SZ-1+MD:0] scw0_symdata; // 1 codeword, SymbolSize*SymbolCount+MD bits data
    wire [SYM_CRC*S_SZ-1:0] scw_symdata[CW-2:0]; // CW-1 codewords, SymbolSize*SymbolCount bits data
    wire [SHB-MD:0] scw0_symcrc; // 1 codeword, SymbolSize-MD bit CRC
    wire [SHB:0] scw_symcrc[CW-2:0]; // CW-1 codewords, SymbolSize bit CRC
    wire [SYM_CRC:0] symxorb[FS_SZ-1:0]; // SymbolCount symbols, SymbolSize*CW bits per symbol
    genvar cw, sym, b;

    // CRC Generation (codeword 0, the one with metadata)
    generate
        for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin // Prepare data for CW0 CRC calculation
            assign scw0_symdata[sym*S_SZ+SHB:sym*S_SZ] = data[sym*FS_SZ+SHB:sym*FS_SZ];
        end
    endgenerate
    assign scw0_symdata[SYM_CRC*S_SZ+MD-1:SYM_CRC*S_SZ] = metadata[MD-1:0];
    calccrc #(.WIDTH(S_SZ-MD), .LENGTH(SYM_CRC*S_SZ+MD)) crcEnc_0 ( // Get CRC for CW0
        .data(scw0_symdata),
        .constants(crcconstants_s[SYM_XOR*S_SZ-1:S_SZ-MD]),
        .crc(scw0_symcrc)
    );
    assign codeword[SYM_CRC*FS_SZ+SHB:0] = { scw0_symcrc, metadata, data }; // Codeword setup

    generate
        // CRC Generation
        for (cw = 0; cw < CW-1; cw = cw + 1) begin
            for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin // Prepare data for CRC calculation
                assign scw_symdata[cw][sym*S_SZ+SHB:sym*S_SZ] = data[sym*FS_SZ+(cw+1)*S_SZ+SHB:sym*FS_SZ+(cw+1)*S_SZ] ^ data[sym*FS_SZ+SHB:sym*FS_SZ];
            end
            calccrc #(.WIDTH(S_SZ), .LENGTH(SYM_CRC*S_SZ)) crcEnc ( // Get CRC for CW 1 to 3
                .data(scw_symdata[cw]),
                .constants(crcconstants[SYM_XOR*S_SZ-1:S_SZ]),
                .crc(scw_symcrc[cw])
            );
            assign codeword[SYM_CRC*FS_SZ+(cw+1)*S_SZ+SHB:SYM_CRC*FS_SZ+(cw+1)*S_SZ] = scw_symcrc[cw] ^ { scw0_symcrc, metadata };
        end        
        // XOR Generation
        for (b = 0; b < FS_SZ; b = b + 1) begin
            for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*FS_SZ+b];
            end
            assign codeword[SYM_XOR*FS_SZ+b] = ^symxorb[b];
        end
    endgenerate
endmodule

module raiddr_decode #(
    parameter S_SZ = 16,
    parameter CW = 4,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [S_SZ*CW*S_COUNT-1:0] codeword,
    input [S_SZ-1:0] crcconstants[S_SZ*(S_COUNT-1)-1:0],
    input [S_SZ-MD-1:0] crcconstants_s[S_SZ*(S_COUNT-1)-1:0],
    output [S_SZ*CW*(S_COUNT-2)-1:0] data,
    output [MD-1:0] metadata,
    output reg ue,
    output reg ce,
    output reg [S_SZ*CW-1:0] ceMask,
    output reg [S_COUNT-1:0] symMask
);
    localparam FS_SZ = S_SZ*CW; // Full Symbol Size = SymbolSize*CodeWords
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam SHB = S_SZ-1; // Symbol High Bit
    wire [SYM_XOR:0] symxorb[FS_SZ-1:0]; // Used to simplify building the ErrorMask --> SymbolCount symbols, SymbolSize*CodeWords bits
    wire [SHB:0] errmask[CW-1:0]; // Mask of all symbols, showing the full symbol error mask --> CodeWords codewords, SymbolSize bit error mask
    wire [S_SZ*(S_COUNT-1)-1:0] subcodeword[CW-1:0]; // Bits isolated to the sub-codeword up to the CRC bits --> CodeWords codewords, SymbolSize*(SymbolCount-1) bit data
    wire [SHB-MD:0] fullcrcCw_0; // Stores the CRC result from the subcodeword[0] CRC --> 1 codeword, SymbolSize-MetadataBits bit CRC
    wire [SHB:0] fullcrcCw[CW-2:0]; // Stores the CRC results from the subcodewords[CW-1:1] --> CodeWords-1 codewords, SymbolSize bit CRC
    wire [SHB-MD:0] maskcrc_0[SYM_CRC:0]; // Stores the CRC results from the errormask at the Symbol/CW=0 position --> SymbolCount-1 symbols, SymbolSize-MetadataBits bit CRC
    wire [SHB:0] maskcrc[CW-2:0][SYM_CRC:0]; // Stores the CRC results from the errormask at the Symbol/CodeWord position --> CodeWords-1 codewords, SymbolCount-1 symbols, SymbolSize bit CRC
    wire [FS_SZ-1-MD:0] trialdata[SYM_XOR:0]; // Stores the full-symbol masked, adjusted CRC result from errormask and full CRC at each position --> SymbolCount total symbols, SymbolSize*CodeWords-MetadataBits bits/full symbol
    wire allpass; // Indicates all trials pass
    wire nonzeroMask; // Indicates the error mask is nonzero
    wire noError; // Indicates the conditions are met for no error detection
    wire uee, uez, uef; // Indicates two conditions for uncorrectable errors
    wire [SYM_XOR-1:0] uesym; // Indicates a UE is detected because two positions pass --> SymbolCount symbols
    wire [SYM_XOR:0] cesym; // Indicates a CE at a specific location --> SymbolCount symbols
    genvar cw, sym, b;

    generate // Get the error mask
        for (b = 0; b < FS_SZ; b = b + 1) begin // Create ceMask (returned value)
            for (sym = 0; sym < S_COUNT; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*FS_SZ+b];
            end
            assign ceMask[b] = ^symxorb[b];
        end
        for (cw = 0; cw < CW; cw = cw + 1) begin // Create errmask (from ceMask)
            assign errmask[cw] = ceMask[cw*S_SZ+SHB:cw*S_SZ];
        end
    endgenerate
    assign nonzeroMask = |ceMask; // If any bit is high in ceMask, then mask is nonzero

    generate // Split the codeword into subcodewords for CRC calculations
        for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin // Get the full subcodeword for CW=0
            assign subcodeword[0][sym*S_SZ+SHB:sym*S_SZ] = codeword[sym*FS_SZ+SHB:sym*FS_SZ];
        end
        for (cw = 1; cw < CW; cw = cw + 1) begin // Get the full subcodewords for CW=1-3
            for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin // Assign sub-CW for symbols 0 to S_COUNT-1
                assign subcodeword[cw][sym*S_SZ+SHB:sym*S_SZ] = codeword[sym*FS_SZ+cw*S_SZ+SHB:sym*FS_SZ+cw*S_SZ] ^ codeword[sym*FS_SZ+SHB:sym*FS_SZ];
            end
        end
    endgenerate

    generate // Get the CRC values (full codeword CRC and errmask CRC and mixed)...
        calccrc #(.WIDTH(S_SZ-MD), .LENGTH(SYM_XOR*S_SZ)) fullcrcDec_0 (
            .data(subcodeword[0]),
            .constants(crcconstants_s[SYM_XOR*S_SZ-1:0]),
            .crc(trialdata[SYM_XOR][SHB-MD:0])
        ); // Get Full CRC for CW=0 --> Results become trial data for the last (XOR) symbol
        for (cw = 1; cw < CW; cw = cw + 1) begin // Get Full CRC for CW 1 - CW --> Results become trial data for the last (XOR) symbol
            calccrc #(.WIDTH(S_SZ), .LENGTH(SYM_XOR*S_SZ)) fullcrcDec (
                .data(subcodeword[cw]),
                .constants(crcconstants[SYM_XOR*S_SZ-1:0]),
                .crc(trialdata[SYM_XOR][cw*S_SZ-MD+SHB:cw*S_SZ-MD])
            );
        end
        assign symMask[SYM_XOR] = ~|trialdata[SYM_XOR];

        // Calculate the error mask CRCs and mix value (tells us if errmask CRC matches the full CRC)
        for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
            calccrc #(.WIDTH(S_SZ-MD), .LENGTH(S_SZ)) maskcrcDec_0 (
                .data(errmask[0]),
                .constants(crcconstants_s[sym*S_SZ+SHB:sym*S_SZ]),
                .crc(maskcrc_0[sym])
            ); // Get Mask CRC values for CW=0
            assign trialdata[sym][SHB-MD:0] = maskcrc_0[sym] ^ trialdata[SYM_XOR][SHB-MD:0];
            for (cw = 1; cw < CW; cw = cw + 1) begin
                calccrc #(.WIDTH(S_SZ), .LENGTH(S_SZ)) maskcrcDec (
                    .data(errmask[cw] ^ errmask[0]),
                    .constants(crcconstants[sym*S_SZ+SHB:sym*S_SZ]),
                    .crc(maskcrc[cw-1][sym])
                );
                assign trialdata[sym][cw*S_SZ-MD+SHB:cw*S_SZ-MD] = maskcrc[cw-1][sym] ^ trialdata[SYM_XOR][cw*S_SZ-MD+SHB:cw*S_SZ-MD];
            end
            assign symMask[sym] = ~|trialdata[sym];
        end
    endgenerate

    // symMask[x] holds the value which tells us if the trial passed (1) or failed (0)
    // If all trials pass and the error mask is zero, then we have no errors
    // If all trials pass and the error mask is nonzero, then we have an uncorrectable error
    // If one trial fails and the error mask is nonzero, then we have a correctable error
    // Any other combination is an uncorrectable error
    assign allpass = &symMask; // All trials pass
    assign noError = allpass & ~nonzeroMask; // All trials pass, zero mask

    // Calculate UE
    assign uee = allpass & nonzeroMask; // All trials pass, nonzero mask
    assign uez = |symMask & ~allpass & ~nonzeroMask; // Any but not all trials pass, zero mask
    assign uef = ~|symMask; // No trials pass
    generate // Fills uesym with 1 when there is more than one symbol that passes
        assign uesym[0] = ~allpass & symMask[0] & |symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign uesym[sym] = ~allpass & symMask[sym] & |symMask[SYM_XOR:sym+1];
        end
    endgenerate
    assign ue = |uesym | uee | uez | uef;

    // Calculate CE
    generate // Fills cesym with 1 when there is only 1 symbol that passes
        assign cesym[0] = symMask[0] & ~|symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign cesym[sym] = symMask[sym] & ~|symMask[SYM_XOR:sym+1] & ~|symMask[sym-1:0];
        end
        assign cesym[SYM_XOR] = symMask[SYM_XOR] & ~|symMask[SYM_CRC:0];
    endgenerate
    assign ce = |cesym & nonzeroMask;

    // Calculate data
    generate
        for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin
            assign data[sym*FS_SZ+FS_SZ-1:sym*FS_SZ] = codeword[sym*FS_SZ+FS_SZ-1:sym*FS_SZ] ^ ((symMask[sym] & ce) ? ceMask : 0);
        end
    endgenerate

    // Calculate metadata
    assign metadata = codeword[SYM_CRC*FS_SZ+MD-1:SYM_CRC*FS_SZ] ^ ((symMask[SYM_CRC] & ce) ? ceMask[MD-1:0] : 0);
endmodule
