// ** basicraiddr_rtlbase.v **
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Version: 1.0.1
// Author: Brett Dodds (brett.dodds@microsoft.com)
// For appending to .v files generated by raiddrinit

module calccrc #(
    parameter LENGTH = 144,
    parameter WIDTH = 16
) (
    input [LENGTH-1:0] data,
    input [WIDTH-1:0] constants[LENGTH-1:0],
    output [WIDTH-1:0] crc
);
    wire [LENGTH-1:0] xorbit[WIDTH-1:0];
    genvar l, b;
    generate
        for (b = 0; b < WIDTH; b = b + 1) begin
            for (l = 0; l < LENGTH; l = l + 1) begin
                assign xorbit[b][l] = data[l] ? constants[l][b] : 0;
            end
            assign crc[b] = ^xorbit[b];
        end
    endgenerate
endmodule

module raiddr_encode #(
    parameter S_SZ = 16,
    parameter CW = 4,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [(S_COUNT-2)*S_SZ*CW-1:0] data,
    input [MD-1:0] metadata,
    input [S_SZ-1:0] crcconstants[(S_COUNT-1)*S_SZ-1:0],
    input [S_SZ-MD-1:0] crcconstants_s[(S_COUNT-1)*S_SZ-1:0],
    output [S_COUNT*S_SZ*CW-1:0] codeword
);
    localparam FS_SZ = S_SZ*CW; // Full Symbol Size = SymbolSize*CodeWords
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam SHB = S_SZ-1; // Symbol High Bit
    wire [SYM_CRC*S_SZ-1+MD:0] scw0_symdata; // 1 codeword, SymbolSize*SymbolCount+MD bits data
    wire [SYM_CRC*S_SZ-1:0] scw_symdata[CW-2:0]; // CW-1 codewords, SymbolSize*SymbolCount bits data
    wire [SHB-MD:0] scw0_symcrc; // 1 codeword, SymbolSize-MD bit CRC
    wire [SHB:0] scw_symcrc[CW-2:0]; // CW-1 codewords, SymbolSize bit CRC
    wire [SYM_CRC:0] symxorb[FS_SZ-1:0]; // SymbolCount symbols, SymbolSize*CW bits per symbol
    genvar cw, sym, b;

    // CRC Generation (codeword 0, the one with metadata)
    generate
        for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin // Prepare data for CW0 CRC calculation
            assign scw0_symdata[sym*S_SZ+SHB:sym*S_SZ] = data[sym*FS_SZ+SHB:sym*FS_SZ];
        end
    endgenerate
    assign scw0_symdata[SYM_CRC*S_SZ+MD-1:SYM_CRC*S_SZ] = metadata[MD-1:0];
    calccrc #(.WIDTH(S_SZ-MD), .LENGTH(SYM_CRC*S_SZ+MD)) crcEnc_0 ( // Get CRC for CW0
        .data(scw0_symdata),
        .constants(crcconstants_s[SYM_XOR*S_SZ-1:S_SZ-MD]),
        .crc(scw0_symcrc)
    );
    assign codeword[SYM_CRC*FS_SZ+SHB:0] = { scw0_symcrc, metadata, data }; // Codeword setup

    generate
        // CRC Generation
        for (cw = 0; cw < CW-1; cw = cw + 1) begin
            for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin // Prepare data for CRC calculation
                assign scw_symdata[cw][sym*S_SZ+SHB:sym*S_SZ] = data[sym*FS_SZ+(cw+1)*S_SZ+SHB:sym*FS_SZ+(cw+1)*S_SZ] ^ data[sym*FS_SZ+SHB:sym*FS_SZ];
            end
            calccrc #(.WIDTH(S_SZ), .LENGTH(SYM_CRC*S_SZ)) crcEnc ( // Get CRC for CW 1 to 3
                .data(scw_symdata[cw]),
                .constants(crcconstants[SYM_XOR*S_SZ-1:S_SZ]),
                .crc(scw_symcrc[cw])
            );
            assign codeword[SYM_CRC*FS_SZ+(cw+1)*S_SZ+SHB:SYM_CRC*FS_SZ+(cw+1)*S_SZ] = scw_symcrc[cw] ^ { scw0_symcrc, metadata };
        end        
        // XOR Generation
        for (b = 0; b < FS_SZ; b = b + 1) begin
            for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*FS_SZ+b];
            end
            assign codeword[SYM_XOR*FS_SZ+b] = ^symxorb[b];
        end
    endgenerate
endmodule

module raiddr_decode #(
    parameter S_SZ = 16,
    parameter CW = 4,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [S_SZ*CW*S_COUNT-1:0] codeword,
    input [S_SZ-1:0] crcconstants[S_SZ*(S_COUNT-1)-1:0],
    input [S_SZ-MD-1:0] crcconstants_s[S_SZ*(S_COUNT-1)-1:0],
    output [S_SZ*CW*(S_COUNT-2)-1:0] data,
    output [MD-1:0] metadata,
    output reg ue,
    output reg ce,
    output reg [S_SZ*CW-1:0] ceMask,
    output reg [S_COUNT-1:0] symMask
);
    localparam FS_SZ = S_SZ*CW; // Full Symbol Size = SymbolSize*CodeWords
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam SHB = S_SZ-1; // Symbol High Bit
    wire [SYM_XOR:0] symxorb[FS_SZ-1:0]; // Used to simplify building the ErrorMask --> SymbolCount symbols, SymbolSize*CodeWords bits
    wire [SHB:0] errmask[CW-1:0]; // Mask of all symbols, showing the full symbol error mask --> CodeWords codewords, SymbolSize bit error mask
    wire [S_SZ*(S_COUNT-1)-1:0] subcodeword[CW-1:0]; // Bits isolated to the sub-codeword up to the CRC bits --> CodeWords codewords, SymbolSize*(SymbolCount-1) bit data
    wire [SHB-MD:0] fullcrcCw_0; // Stores the CRC result from the subcodeword[0] CRC --> 1 codeword, SymbolSize-MetadataBits bit CRC
    wire [SHB:0] fullcrcCw[CW-2:0]; // Stores the CRC results from the subcodewords[CW-1:1] --> CodeWords-1 codewords, SymbolSize bit CRC
    wire [SHB-MD:0] maskcrc_0[SYM_CRC:0]; // Stores the CRC results from the errormask at the Symbol/CW=0 position --> SymbolCount-1 symbols, SymbolSize-MetadataBits bit CRC
    wire [SHB:0] maskcrc[CW-2:0][SYM_CRC:0]; // Stores the CRC results from the errormask at the Symbol/CodeWord position --> CodeWords-1 codewords, SymbolCount-1 symbols, SymbolSize bit CRC
    wire [FS_SZ-1-MD:0] trialdata[SYM_XOR:0]; // Stores the full-symbol masked, adjusted CRC result from errormask and full CRC at each position --> SymbolCount total symbols, SymbolSize*CodeWords-MetadataBits bits/full symbol
    wire allpass; // Indicates all trials pass
    wire nonzeroMask; // Indicates the error mask is nonzero
    wire noError; // Indicates the conditions are met for no error detection
    wire uee, uez, uef; // Indicates two conditions for uncorrectable errors
    wire [SYM_XOR-1:0] uesym; // Indicates a UE is detected because two positions pass --> SymbolCount symbols
    wire [SYM_XOR:0] cesym; // Indicates a CE at a specific location --> SymbolCount symbols
    genvar cw, sym, b;

    generate // Get the error mask
        for (b = 0; b < FS_SZ; b = b + 1) begin // Create ceMask (returned value)
            for (sym = 0; sym < S_COUNT; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*FS_SZ+b];
            end
            assign ceMask[b] = ^symxorb[b];
        end
        for (cw = 0; cw < CW; cw = cw + 1) begin // Create errmask (from ceMask)
            assign errmask[cw] = ceMask[cw*S_SZ+SHB:cw*S_SZ];
        end
    endgenerate
    assign nonzeroMask = |ceMask; // If any bit is high in ceMask, then mask is nonzero

    generate // Split the codeword into subcodewords for CRC calculations
        for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin // Get the full subcodeword for CW=0
            assign subcodeword[0][sym*S_SZ+SHB:sym*S_SZ] = codeword[sym*FS_SZ+SHB:sym*FS_SZ];
        end
        for (cw = 1; cw < CW; cw = cw + 1) begin // Get the full subcodewords for CW=1-3
            for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin // Assign sub-CW for symbols 0 to S_COUNT-1
                assign subcodeword[cw][sym*S_SZ+SHB:sym*S_SZ] = codeword[sym*FS_SZ+cw*S_SZ+SHB:sym*FS_SZ+cw*S_SZ] ^ codeword[sym*FS_SZ+SHB:sym*FS_SZ];
            end
        end
    endgenerate

    generate // Get the CRC values (full codeword CRC and errmask CRC and mixed)...
        calccrc #(.WIDTH(S_SZ-MD), .LENGTH(SYM_XOR*S_SZ)) fullcrcDec_0 (
            .data(subcodeword[0]),
            .constants(crcconstants_s[SYM_XOR*S_SZ-1:0]),
            .crc(trialdata[SYM_XOR][SHB-MD:0])
        ); // Get Full CRC for CW=0 --> Results become trial data for the last (XOR) symbol
        for (cw = 1; cw < CW; cw = cw + 1) begin // Get Full CRC for CW 1 - CW --> Results become trial data for the last (XOR) symbol
            calccrc #(.WIDTH(S_SZ), .LENGTH(SYM_XOR*S_SZ)) fullcrcDec (
                .data(subcodeword[cw]),
                .constants(crcconstants[SYM_XOR*S_SZ-1:0]),
                .crc(trialdata[SYM_XOR][cw*S_SZ-MD+SHB:cw*S_SZ-MD])
            );
        end
        assign symMask[SYM_XOR] = ~|trialdata[SYM_XOR];

        // Calculate the error mask CRCs and mix value (tells us if errmask CRC matches the full CRC)
        for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
            calccrc #(.WIDTH(S_SZ-MD), .LENGTH(S_SZ)) maskcrcDec_0 (
                .data(errmask[0]),
                .constants(crcconstants_s[sym*S_SZ+SHB:sym*S_SZ]),
                .crc(maskcrc_0[sym])
            ); // Get Mask CRC values for CW=0
            assign trialdata[sym][SHB-MD:0] = maskcrc_0[sym] ^ trialdata[SYM_XOR][SHB-MD:0];
            for (cw = 1; cw < CW; cw = cw + 1) begin
                calccrc #(.WIDTH(S_SZ), .LENGTH(S_SZ)) maskcrcDec (
                    .data(errmask[cw] ^ errmask[0]),
                    .constants(crcconstants[sym*S_SZ+SHB:sym*S_SZ]),
                    .crc(maskcrc[cw-1][sym])
                );
                assign trialdata[sym][cw*S_SZ-MD+SHB:cw*S_SZ-MD] = maskcrc[cw-1][sym] ^ trialdata[SYM_XOR][cw*S_SZ-MD+SHB:cw*S_SZ-MD];
            end
            assign symMask[sym] = ~|trialdata[sym];
        end
    endgenerate

    // symMask[x] holds the value which tells us if the trial passed (1) or failed (0)
    // If all trials pass and the error mask is zero, then we have no errors
    // If all trials pass and the error mask is nonzero, then we have an uncorrectable error
    // If one trial fails and the error mask is nonzero, then we have a correctable error
    // Any other combination is an uncorrectable error
    assign allpass = &symMask; // All trials pass
    assign noError = allpass & ~nonzeroMask; // All trials pass, zero mask

    // Calculate UE
    assign uee = allpass & nonzeroMask; // All trials pass, nonzero mask
    assign uez = |symMask & ~allpass & ~nonzeroMask; // Any but not all trials pass, zero mask
    assign uef = ~|symMask; // No trials pass
    generate // Fills uesym with 1 when there is more than one symbol that passes
        assign uesym[0] = ~allpass & symMask[0] & |symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign uesym[sym] = ~allpass & symMask[sym] & |symMask[SYM_XOR:sym+1];
        end
    endgenerate
    assign ue = |uesym | uee | uez | uef;

    // Calculate CE
    generate // Fills cesym with 1 when there is only 1 symbol that passes
        assign cesym[0] = symMask[0] & ~|symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign cesym[sym] = symMask[sym] & ~|symMask[SYM_XOR:sym+1] & ~|symMask[sym-1:0];
        end
        assign cesym[SYM_XOR] = symMask[SYM_XOR] & ~|symMask[SYM_CRC:0];
    endgenerate
    assign ce = |cesym & nonzeroMask;

    // Calculate data
    generate
        for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin
            assign data[sym*FS_SZ+FS_SZ-1:sym*FS_SZ] = codeword[sym*FS_SZ+FS_SZ-1:sym*FS_SZ] ^ ((symMask[sym] & ce) ? ceMask : 0);
        end
    endgenerate

    // Calculate metadata
    assign metadata = codeword[SYM_CRC*FS_SZ+MD-1:SYM_CRC*FS_SZ] ^ ((symMask[SYM_CRC] & ce) ? ceMask[MD-1:0] : 0);
endmodule