// ** basicraiddr_rtlbase_1cw.v **
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Version: 1.0.0
// Author: Brett Dodds (brett.dodds@microsoft.com)
// For appending to single-codeword .v files generated by raiddrinit

module calccrc #(
    parameter LENGTH = 144,
    parameter WIDTH = 16
) (
    input [LENGTH-1:0] data,
    input [WIDTH-1:0] constants[LENGTH-1:0],
    output [WIDTH-1:0] crc
);
    wire [LENGTH-1:0] xorbit[WIDTH-1:0];
    genvar l, b;
    generate
        for (b = 0; b < WIDTH; b = b + 1) begin
            for (l = 0; l < LENGTH; l = l + 1) begin
                assign xorbit[b][l] = data[l] ? constants[l][b] : 0;
            end
            assign crc[b] = ^xorbit[b];
        end
    endgenerate
endmodule

module raiddr_encode #(
    parameter S_SZ = 64,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [(S_COUNT-2)*S_SZ-1:0] data,
    input [MD-1:0] metadata,
    input [S_SZ-MD-1:0] crcconstants[(S_COUNT-1)*S_SZ-1:0],
    output [S_COUNT*S_SZ-1:0] codeword
);
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam DATA_END = SYM_CRC*S_SZ-1+MD; // End of data/metadata bits
    localparam CRC_START = SYM_CRC*S_SZ+MD; // Start of CRC bits
    localparam CRC_END = SYM_XOR*S_SZ-1; // End of CRC bits
    localparam XOR_START = SYM_XOR*S_SZ; // Start of XOR bits
    localparam XOR_END = S_COUNT*S_SZ-1; // End of XOR bits
    wire [SYM_CRC:0] symxorb[S_SZ-1:0]; // SymbolCount symbols, SymbolSize*CW bits per symbol
    genvar b, sym;

    // CRC Generation
    assign codeword[SYM_CRC*S_SZ-1+MD:0] = { metadata, data }; // Prepare data for CW0 CRC calculation
    calccrc #(.WIDTH(S_SZ-MD), .LENGTH(DATA_END+1)) crcEnc ( // Get CRC for CW0
        .data(codeword[DATA_END:0]),
        .constants(crcconstants[CRC_END:S_SZ-MD]),
        .crc(codeword[CRC_END:CRC_START])
    );
    // XOR Generation
    generate
        for (b = 0; b < S_SZ; b = b + 1) begin
            for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*S_SZ+b];
            end
            assign codeword[XOR_START+b] = ^symxorb[b];
        end
    endgenerate
endmodule

module raiddr_decode #(
    parameter S_SZ = 16,
    parameter MD = 3,
    parameter S_COUNT = 10
)(
    input [S_COUNT*S_SZ-1:0] codeword,
    input [S_SZ-MD-1:0] crcconstants[(S_COUNT-1)*S_SZ-1:0],
    output [(S_COUNT-2)*S_SZ-1:0] data,
    output [MD-1:0] metadata,
    output reg ue,
    output reg ce,
    output reg [S_SZ-1:0] ceMask,
    output reg [S_COUNT-1:0] symMask
);
    localparam SYM_CRC = S_COUNT-2; // Symbol # of CRC symbol
    localparam SYM_XOR = S_COUNT-1; // Symbol # of XOR symbol
    localparam DATA_END = SYM_CRC*S_SZ-1+MD; // End of data/metadata bits
    localparam CRC_START = SYM_CRC*S_SZ+MD; // Start of CRC bits
    localparam CRC_END = SYM_XOR*S_SZ-1; // End of CRC bits
    localparam CRC_SIZE = S_SZ-MD; // Size of CRC bits
    localparam XOR_START = SYM_XOR*S_SZ; // Start of XOR bits
    localparam XOR_END = S_COUNT*S_SZ-1; // End of XOR bits
    localparam SHB = S_SZ-1; // Symbol High Bit
    wire [SYM_XOR:0] symxorb[S_SZ-1:0]; // Used to simplify building the ErrorMask --> SymbolCount symbols, SymbolSize*CodeWords bits
    wire [SHB-MD:0] fullcrc; // Stores the CRC result from the codeword CRC --> SymbolSize-MetadataBits bit CRC
    wire [SHB-MD:0] maskcrc[SYM_CRC:0]; // Stores the CRC results from the errormask at the Symbol/CW=0 position --> SymbolCount-1 symbols, SymbolSize-MetadataBits bit CRC
    wire [SHB-MD:0] trialdata[SYM_XOR:0]; // Stores the full-symbol masked, adjusted CRC result from errormask and full CRC at each position --> SymbolCount total symbols, SymbolSize*CodeWords-MetadataBits bits/full symbol
    wire allpass; // Indicates all trials pass
    wire nonzeroMask; // Indicates the error mask is nonzero
    wire noError; // Indicates the conditions are met for no error detection
    wire uee, uez, uef; // Indicates two conditions for uncorrectable errors
    wire [SYM_XOR-1:0] uesym; // Indicates a UE is detected because two positions pass --> SymbolCount symbols
    wire [SYM_XOR:0] cesym; // Indicates a CE at a specific location --> SymbolCount symbols
    genvar b, sym;

    generate // Get the error mask
        for (b = 0; b < S_SZ; b = b + 1) begin // Create ceMask (returned value)
            for (sym = 0; sym < S_COUNT; sym = sym + 1) begin
                assign symxorb[b][sym] = codeword[sym*S_SZ+b];
            end
            assign ceMask[b] = ^symxorb[b];
        end
    endgenerate
    assign nonzeroMask = |ceMask; // If any bit is high in ceMask, then mask is nonzero

    generate // Get the CRC values (full codeword CRC and errmask CRC and mixed)...
        calccrc #(.WIDTH(CRC_SIZE), .LENGTH(CRC_END+1)) fullcrcDec (
            .data(codeword[CRC_END:0]),
            .constants(crcconstants[CRC_END:0]),
            .crc(trialdata[SYM_XOR][CRC_SIZE-1:0])
        ); // Get Full CRC --> Results become trial data for the last (XOR) symbol since it doesn't participate in the CRC calculation
        assign symMask[SYM_XOR] = ~|trialdata[SYM_XOR];

        // Calculate the error mask CRCs and mix value (tells us if errmask CRC matches the full CRC)
        for (sym = 0; sym < SYM_XOR; sym = sym + 1) begin
            calccrc #(.WIDTH(CRC_SIZE), .LENGTH(S_SZ)) maskcrcDec (
                .data(ceMask),
                .constants(crcconstants[sym*S_SZ+SHB:sym*S_SZ]),
                .crc(maskcrc[sym])
            ); // Get Mask CRC values for CW=0
            //assign trialdata[sym][CRC_SIZE-1:0] = maskcrc[sym] ^ trialdata[SYM_XOR][CRC_SIZE-1:0];
            assign trialdata[sym] = maskcrc[sym] ^ trialdata[SYM_XOR];
            assign symMask[sym] = ~|trialdata[sym];
        end
    endgenerate

    // symMask[x] holds the value which tells us if the trial passed (1) or failed (0)
    // If all trials pass and the error mask is zero, then we have no errors
    // If all trials pass and the error mask is nonzero, then we have an uncorrectable error
    // If one trial fails and the error mask is nonzero, then we have a correctable error
    // Any other combination is an uncorrectable error
    assign allpass = &symMask; // All trials pass
    assign noError = allpass & ~nonzeroMask; // All trials pass, zero mask

    // Calculate UE
    assign uee = allpass & nonzeroMask; // All trials pass, nonzero mask
    assign uez = |symMask & ~allpass & ~nonzeroMask; // Any but not all trials pass, zero mask
    assign uef = ~|symMask; // No trials pass
    generate // Fills uesym with 1 when there is more than one symbol that passes
        assign uesym[0] = ~allpass & symMask[0] & |symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign uesym[sym] = ~allpass & symMask[sym] & |symMask[SYM_XOR:sym+1];
        end
    endgenerate
    assign ue = |uesym | uee | uez | uef;

    // Calculate CE
    generate // Fills cesym with 1 when there is only 1 symbol that passes
        assign cesym[0] = symMask[0] & ~|symMask[SYM_XOR:1];
        for (sym = 1; sym < SYM_XOR; sym = sym + 1) begin
            assign cesym[sym] = symMask[sym] & ~|symMask[SYM_XOR:sym+1] & ~|symMask[sym-1:0];
        end
        assign cesym[SYM_XOR] = symMask[SYM_XOR] & ~|symMask[SYM_CRC:0];
    endgenerate
    assign ce = |cesym & nonzeroMask;

    // Calculate data
    generate
        for (sym = 0; sym < SYM_CRC; sym = sym + 1) begin
            assign data[sym*S_SZ+SHB:sym*S_SZ] = codeword[sym*S_SZ+SHB:sym*S_SZ] ^ ((symMask[sym] & ce) ? ceMask : 0);
        end
    endgenerate

    // Calculate metadata
    assign metadata = codeword[SYM_CRC*S_SZ+MD-1:SYM_CRC*S_SZ] ^ ((symMask[SYM_CRC] & ce) ? ceMask[MD-1:0] : 0);
endmodule